---
name: "HassBox 应用商店 - 加载项下载助手"
version: "0.0.1"
slug: hassbox_store_downloader
description: "HassBox 应用商店下载加载项时会自动启动，下载完成后会自动停止。"
url: "https://hassbox.cn"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - addons:rw
ports:
  80/tcp: 9222
image: "hassbox/{arch}-hassbox-store-downloader"